# Site settings
title: James Sutton
email: james.sutton1211@gmail.com
description: Just my little ML and data science blog, I like trying to tackle really hard problems, math and stats are super fun!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zeryx.github.io" # the base hostname & protocol for your site
twitter_username: zeryx
github_username:  zeryx

# Build settings
markdown: kramdown
